recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    ShoppingItemListView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    new_item,
    ShoppingItemListView,
    delete_all_items,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("shopping_items/create/", new_item, name="shopping_item_new"),
    path(
        "shopping_items/",
        ShoppingItemListView.as_view(),
        name="shopping_items_list",
    ),
    path(
        "shopping_items/delete/", delete_all_items, name="shopping_items_delete"
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models

from django.conf import settings

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
        null=True,
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.IntegerField(validators=[MinValueValidator(1)], null=True)

    def __str__(self):
        return self.name + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(100)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey(
        "FoodItem", related_name="ingredients", on_delete=models.PROTECT
    )

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL, related_name="shopping_item", on_delete=models.CASCADE
    )
    food_item = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

recipes/forms.py
from django import forms

from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from platformdirs import user_cache_dir
from recipes.forms import RatingForm
from recipes.models import Ingredient, ShoppingItem, FoodItem, Recipe
from django.db import IntegrityError
from django.views.decorators.http import require_http_methods


def log_rating(request, recipe_id):
    if request.method == "POST":
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.recipe = Recipe.objects.get(pk=recipe_id)
            rating.save()
    return redirect("recipe_detail", pk=recipe_id)


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 2


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        ingredients = []
        for item in self.request.user.shopping_item.all():
            ingredients.append(item.food_item)
        context["servings"] = self.request.GET.get("servings")
        context["food_in_shopping_list"] = ingredients

        return context


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "author", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")


# shopping items create function
@require_http_methods(["POST"])
def new_item(request):
    ingredient_id = request.POST.get("ingredient_id")
    ingredient = Ingredient.objects.get(id=ingredient_id)
    user = request.user
    ShoppingItem.objects.create(food_item=ingredient.food, user=user)
    # except IntegrityError:
    #     print("Integrity Error thrown")
    #     pass

    return redirect("recipe_detail", pk=ingredient.recipe.id)


# shopping items list function
class ShoppingItemListView(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "shopping_items/list.html"

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


# shopping items delete function
def delete_all_items(request):
    user = request.user
    ShoppingItem.objects.filter(user=user).delete()
    return redirect("shopping_items_list")

recipes/templates/base.html
{% load static %}
{% load markdownify %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        {% endblock title %}
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <header>
            <p> Logged in as - {{user}} </p>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Recipes</a>
                    </li>
                    <li>
                        <a href="{% url 'tags_list' %}">Tags</a>
                    </li>
                    <li>
                        <a href="{% url 'recipe_new' %}">Write a recipe</a>
                    </li>
                    

                    {% if user.is_staff %}
                    <li>
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'mealplan_list' %}">Meal Plans</a>
                    </li>
                    <li>
                      <a href="{% url 'shopping_items_list' %}">
                        Shop List ({{ user.shopping_item.all|length }})
                      </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}

    </body>
</html>

recipes/templates/paginate.html
{% load static %}
{% load markdownify %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
  {% endblock title %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <p> Logged in as - {{user}} </p>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Recipes</a>
        </li>
        <li>
          <a href="{% url 'tags_list' %}">Tags</a>
        </li>
        <li>
          <a href="{% url 'mealplan_list' %}">Meal Plans</a>
        </li>
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li>
          <a href="{% url 'recipe_new' %}">Write a recipe</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        <li>
          <a href="{% url 'shopping_items_list' %}">
            Shop List ({{ user.shopping_item.all|length }})
          </a>
        </li>
        {% endif %}
        {% if user.is_authenticated is False %}
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {%block pagination%}
    {%endblock pagination%}
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>